### ISSUE TITLE
Preprocess scripts using only CPU

### ISSUE THREAD

**Issue by TrycsPublic** [CorentinJ/Real-Time-Voice-Cloning#1073]
It estimated to take over 123 hours to preprocess synthesizer, can you make it run on GPU? I have 56vCPU all maxed out, and it still takes so long.

80000+ speakers | 4.30speaker/sec

It’s not like im in a hurry, at this rate it would cost me over $1000 to just preprocess the synthesizer.

**Comment by raccoonML** [comment]
Are you preprocessing mels or embeds? Can you confirm whether you want it on CPU or GPU? It's ambiguous.

**Comment by TrycsPublic** [comment]
Preprocess of audio, is on CPU. Preprocess of embeds are in GPU, but pre-embeds only support 1 GPU I assume.

**Comment by raccoonML** [comment]
For preprocess embeds on CPU, try changing [this line](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/0713f860a3dd41afb56e83cff84dbdf589d5e11a/synthesizer/preprocess.py#L231) to:
```
encoder.load_model(encoder_model_fpath, device="cpu")
```

**Comment by TrycsPublic** [comment]
> For preprocess embeds on CPU, try changing [this line](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/0713f860a3dd41afb56e83cff84dbdf589d5e11a/synthesizer/preprocess.py#L231) to:
> 
> ```
> encoder.load_model(encoder_model_fpath, device="cpu")
> ```

I think you are confused, the goal is if we can process the audio with GPU+CPU.
2nd, to support multi-GPU processing of embeds.

**Comment by raccoonML** [comment]
> I think you are confused, the goal is if we can process the audio with GPU+CPU.

Preprocess audio on GPU is a lot of work to set up. In addition to rewriting the melspectogram routine for GPU, you'll need to batch the audios to get a real speed improvement. That means padding audios so each batch has the same number of audio timesteps, and removing the padding portion in each of the output mels.

You can also consider preprocess in real time during training, if you have enough CPUs to keep your GPU at full load. This one requires the [dataloader](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/0713f860a3dd41afb56e83cff84dbdf589d5e11a/synthesizer/synthesizer_dataset.py#L8) and [training routine](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/0713f860a3dd41afb56e83cff84dbdf589d5e11a/synthesizer/train.py#L27-L28) to be modified. Unfortunately, this one is not trivial either.

> 2nd, to support multi-GPU processing of embeds.

The GPU speedup for preprocess embeds is not that much on a normal system because the bottleneck is disk I/O. From a cost perspective, CPU-only embed processing may be cheaper and almost as fast.
