### ISSUE TITLE
problem with utils.argutils  in python 3.6

### ISSUE THREAD

**Issue by alain2208** [CorentinJ/Real-Time-Voice-Cloning#13]
Hi under win 10 64 bits trying using python 3.6 it failed to import the print_args wiht the fact that he can't find the argutils.
think i have a relative import error but can't solve it

btw nice job on what i heard on the youtube demo
if i mnaully try to import the utils from the root dir seems he load another utils files

**Comment by CorentinJ** [comment]
Thank you. Are you sure you're executing the scripts from the root of the repo as working directory (i.e. the directory that contains the scripts)? I suspect that's the problem, but if it's not you can simply comment out the lines that use `utils.argutils` (the import statement and the print_args call) because they're simply there to display a fancy output. If that fixes it, let me know.

**Comment by alain2208** [comment]
> re you sure you're executing the scripts from the root of the repo as working directory (i.e. the directory that contains the scripts)? I suspect that's the problem

what do you mean i should not run it from the folder?
by removing the line it starts. No wi should investiagte cudnn that is supposed to be on my pc but failed. but thaks for quick help

**Comment by TheButlah** [comment]
I have this same issue. I didn't want to have to comment out the import, so I added an `__init__.py` file to the `utils` folder. @CorentinJ Does that sound like a reasonable fix to you? Python's import semantics are a mystery to me

**Comment by TheButlah** [comment]
Update: Inexplicably, this works on my server even without __init__.py. Both are anaconda 3.7, the only difference is the server is using CUDA and GPUS and my laptop isnt. 

????

**Comment by CorentinJ** [comment]
Oh yeah there's definitely supposed to be an `__init__.py` file there. I overlooked that, thanks. Fixing it now.
