### ISSUE TITLE
Undefined names: run_live() and linear_dir

### ISSUE THREAD

**Issue by cclauss** [CorentinJ/Real-Time-Voice-Cloning#15]
Where are __run_live()__ and __linear_dir__ defined?  Are these missing imports?

[flake8](http://flake8.pycqa.org) testing of https://github.com/CorentinJ/Real-Time-Voice-Cloning on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./synthesizer/synthesize.py:110:9: F821 undefined name 'run_live'
        run_live(args, checkpoint_path, hparams)
        ^
./synthesizer/train.py:347:46: F821 undefined name 'linear_dir'
                        np.save(os.path.join(linear_dir, linear_filename), linear_prediction.T,
                                             ^
2     F821 undefined name 'run_live'
2
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by CorentinJ** [comment]
Oh yeah these are functions from Rayahane's tacotron implementation that I've butchered away. I'm not religious on flake8 but I guess it wouldn't hurt to clean some things up. I'll see to it.

**Comment by cclauss** [comment]
Thx.

**Comment by cclauss** [comment]
> I'm not religious on flake8

Me neither but I do like __--select=E9,F63,F72,F82__.  Most of the others are "_style violations_" that can be autofixed with a run of __python/black__.

**Comment by CorentinJ** [comment]
Well thank you for looking into it. I've fixed those in 0908e4d30d3fae78b4cbd69cd09c20f0a98c4dd0.

I do think that some of the thousand style violations are problematic. E.g. I've been trying to fix (manually) the inconsistent indents in Rahayne's code and the character limits being broken everywhere, and I didn't think of using a tool that would automate that. I will look into using black, but I feel like I might regret it if I change a thousand lines at once and if I don't look at the diff after (I assume that the semantics are not changed, but still). Since you seem to have experience with that, do you think that's it's the right approach?

**Comment by cclauss** [comment]
If you are doing this by hand then check out https://black.readthedocs.io

You could do just the worst files or the worst directories.

**Comment by cclauss** [comment]
Nice work.

Yes the semantics are not changed by black.
