### ISSUE TITLE
Request: Add dataset support for The Spoken Wikipedia Corpora

### ISSUE THREAD

**Issue by raanubis** [CorentinJ/Real-Time-Voice-Cloning#183]
Hi,

May you implement the mentioned data set as source?
I'm tried but i'm to st*p*d.

It has a swc file (you could also create with the masterfile https://bitbucket.org/natsuhh/swc/raw/master/master_script.sh for every language swc files and the audio), in it are the start and endpoint of a word stored.

As example:
'n pronunciation="sixty" start="5540" end="6080"'

but i have the problem to match the start and the endpoint with the soundfile.

I've attached a sample file (src: https://nats.gitlab.io/swc/)

[aligned.txt](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/3790903/aligned.txt)

**Comment by blue-fish** [comment]
I'm going to close this due to inactivity. It's a nice dataset but not in our planned list of things to do. You could submit an issue to https://github.com/pytorch/audio requesting them to add support in [torchaudio.datasets](https://pytorch.org/audio/datasets.html). That would make it much easier to work with.
