### ISSUE TITLE
Bypass the synthesize step

### ISSUE THREAD

**Issue by hawkmoon77** [CorentinJ/Real-Time-Voice-Cloning#193]
In looking at the code, it seems like it might be possible to skip the synthesizing step.  (I'm using the standard datasets but I would like to use an existing wav file and NOT one that was synthesized to create the meLspectrograms.

I'm in the inference.py file and thought I might be able to call the make_spectrogram method instead of the synthesize_spectrograms method, and just point it to my own wav file.  Unfortunately it is not as straight forward as this.  Can someone give me a lead on how to do this, or let me know if this is actually impossible given the overall structure.

Thank you.

**Comment by blue-fish** [comment]
@hawkmoon77 It sounds like what you want to do is a **style transfer** where you take a speaker embedding and apply it to an existing speech wav to change the voice. I touch on it briefly here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/251#issuecomment-653851389

Let's look at the current workflow to understand the different parts:
C-1. file1.wav --> speaker\_encoder (inference) --> embedding
C-2. embedding + text --> synthesizer (inference) --> mel spectrogram (with the voice of the speaker in file1.wav)
C-3. mel spectrogram --> vocoder (inference) --> output.wav

Now let's look at your proposed workflow:
P-1. file1.wav --> speaker\_encoder (inference) --> embedding  (NO CHANGE)
P-2. embedding + file2.wav --> synthesizer (inference) --> mel spectrogram (of file2.wav modified to have the voice of the speaker in file1.wav)
P-3. mel spectrogram --> vocoder (inference) --> output.wav

As I understand it, it's not really possible within the framework of the repo because the synthesizer is designed to text as input and not a wav file. To train your proposed synthesizer model (P-2) you would need a large corpus with thousands of different voices saying the exact same set of phrases. And at that point it's not really a synthesizer but rather a voice transfer engine. (Also, at that point you might combine P-2 and P-3 into a single step and generate the output wavs directly.) Feasible and in some respects likely easier than accomplishing the same thing with text-to-speech, but the lack of an appropriately large and diverse dataset seems to be the obstacle here.

Disclaimer: I am new to this, so take all of the above with a grain of salt.

**Comment by blue-fish** [comment]
Check out [AutoVC](https://github.com/auspicious3000/autovc) ([audio samples](https://auspicious3000.github.io/autovc-demo/)) as an example of voice style transfer. This seems to be what you are looking for.
