### ISSUE TITLE
Would it be possible to synthesize and replace parts of an existing audio clip?

### ISSUE THREAD

**Issue by strich** [CorentinJ/Real-Time-Voice-Cloning#195]
As a game developer we often have to re-record voice over for our games due to minor changes in game design or features. For example, an NPC might reply with "Thanks for killing those *four* blasted rats from my cellar!". However later on we may change the rats from 4 to 3.

I've become very interested in this field of ML for this reason. It appears we have the tech to solve this problem. This project can do this, however I think the final step missing is being able to intelligently replace singular or small numbers of words within an existing audio file (with transcript).

I'd be curious to know if such a thing would be relatively easy to implement here - I would be interested in contributing if we could arrive at a general approach to take.

**Comment by nshmyrev** [comment]
It is easier to resynthesize the whole sentence.

**Comment by strich** [comment]
Technically it would be easier, but the actor has imparted a lot of tone and intent in such VO that no synthesizer is close to capable of inferring and repeating at this point. Being able to replace individual wors or small combinations within an existing file would be the perfect balance of generated voice and artistic intention.

**Comment by nate-moo** [comment]
you could have the ai synthesize the words that you need replacing and replace them manually

**Comment by blue-fish** [comment]
@strich I don't think it would be an easy task to set it up, but one possibility is to use something like the [Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/introduction.html) using your source utterance and transcript as inputs. This would provide alignments for the speech allowing the problematic speech segment to be removed.

Then feed the source utterance into the RVTC toolbox to generate an embedding and replacement speech segment. Splice the replacement in to create the new utterance.

Another possibility is to use a commercial product like the one linked here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/182#issuecomment-548422235

I am going to close this issue due to inactivity, but reopen if you are still interested in doing this.
