### ISSUE TITLE
encoder_preprocess do not preprocess all samples

### ISSUE THREAD

**Issue by LmYjQ** [CorentinJ/Real-Time-Voice-Cloning#203]
I have my own dataset 
![image](https://user-images.githubusercontent.com/12581433/68775649-ce423680-0669-11ea-9d43-5129bace3d56.png)
and my function added
```
def preprocess_aishell(datasets_root: Path, out_dir: Path, skip_existing=False):
    # Initialize the preprocessing
    dataset_name = "aishell"
    dataset_root, logger = _init_preprocess_dataset(dataset_name, datasets_root, out_dir)
    if not dataset_root:
        return

    # Get the speaker directories
    # Preprocess all speakers
    speaker_dirs = list(dataset_root.joinpath("dev").glob("*"))
    _preprocess_speaker_dirs(speaker_dirs, dataset_name, datasets_root, out_dir, "wav",
                             skip_existing, logger)
```
then run the following command
![image](https://user-images.githubusercontent.com/12581433/68775934-3729ae80-066a-11ea-966a-038ffb58ba21.png)
Everything seems perfect, but error occur in the following train step.
Exception: Can't create RandomCycler from an empty collection
![image](https://user-images.githubusercontent.com/12581433/68776162-98ea1880-066a-11ea-89d6-87ef169a6917.png)
because there is nothing in some of the directories.

**Comment by olosen-a** [comment]
I'm not sure if this  is causing your issue, but this is the first thing that popped up in my head. 

It might be that for the empty instances (if there are others that are properly populated), the melspectrograms generated were too short. In the encoder preprocess file, there is a condition to check if the length of the generated melspectrogram was less than the value of 'partials_n_frames', (the value of which I believe was set in the params_data file. If the spectrogram is too short, it is discarded. So that could possibly be your issue. I would try looking at the lengths of the generated spectrograms and comparing with the value of 'partials_n_frames' to see if this can be ruled out or not.

**Comment by LmYjQ** [comment]
> I'm not sure if this is causing your issue, but this is the first thing that popped up in my head.
> 
> It might be that for the empty instances (if there are others that are properly populated), the melspectrograms generated were too short. In the encoder preprocess file, there is a condition to check if the length of the generated melspectrogram was less than the value of 'partials_n_frames', (the value of which I believe was set in the params_data file. If the spectrogram is too short, it is discarded. So that could possibly be your issue. I would try looking at the lengths of the generated spectrograms and comparing with the value of 'partials_n_frames' to see if this can be ruled out or not.

It is exactly what you said, thank you!
