### ISSUE TITLE
Combine with mobile app

### ISSUE THREAD

**Issue by RaghunandanVenkatesh** [CorentinJ/Real-Time-Voice-Cloning#273]
Hey. Is there a possibility of reducing the vocoder time for same voice but different text?

**Comment by blue-fish** [comment]
@RaghunandanVenkatesh It is not really possible. There are three steps to voice cloning:
1. Calculate the embedding from the voice sample
2. Synthesize the mel spectrogram from the embedding + text
3. Convert the mel spectrogram to a wave file using the vocoder

Even if you reuse the embedding from step 1, it turns out that steps 2 and 3 are computationally expensive and must be performed each time the text is changed.
