### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by ShimmerSummer** [CorentinJ/Real-Time-Voice-Cloning#296]
which tensorflow version can work?

**Comment by favarete** [comment]
I'm using 1.14, but think the latest 1.x should be fine too.

**Comment by a3diti** [comment]
I think we can use also tensorflow 2 using the import at the code:
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
Found at [https://www.tensorflow.org/guide/migrate](https://www.tensorflow.org/guide/migrate)

Using **mac** and **tensorflow-gpu** version **1.14.0** is impossible since it does not exists on the pypi directory https://github.com/tensorflow/tensorflow/issues/8251#issuecomment-617080152

**Comment by blue-fish** [comment]
Tensorflow 1.15 is required now.
