### ISSUE TITLE
Tensorflow import error in the Google Colab notebook

### ISSUE THREAD

**Issue by EvanGebo** [CorentinJ/Real-Time-Voice-Cloning#303]
When installing the requirements with pip, I get the following errors which causes tensorflow to not be installed.

`ERROR: tensorflow 2.2.0rc1 has requirement tensorboard<2.2.0,>=2.1.0, but you'll have tensorboard 1.14.0 which is incompatible.`
`ERROR: tensorflow 2.2.0rc1 has requirement tensorflow-estimator<2.3.0,>=2.2.0rc0, but you'll have tensorflow-estimator 1.14.0 which is incompatible.`

**Comment by Tomotori** [comment]
Try replacing `!pip install -r -q requirements.txt `
with
```
%tensorflow_version 1.x
!pip install umap-learn
!pip install visdom
!pip install webrtcvad
!pip install librosa>=0.5.1
!pip install matplotlib>=2.0.2
!pip install numpy>=1.14.0
!pip install scipy>=1.0.0
!pip install tqdm
!pip install sounddevice
!pip install Unidecode
!pip install inflect
!pip install PyQt5
!pip install multiprocess
!pip install numba
```

**Comment by ishaanv** [comment]
@Tomotori Thanks for that fix. Do you know why that change solves those errors?

**Comment by Tomotori** [comment]
Currently, Google Colab defaults to using Tensorflow 2 so we need to first change to Tensorflow 1 (see here for more info : https://colab.research.google.com/notebooks/tensorflow_version.ipynb) . But Google Colab is only working with specific versions of Tensorflow and the version that is imported in the file requirement.txt is too old. So a quick fix is to import everything manually except tensorflow instead of importing through requirement.txt.

**Comment by blue-fish** [comment]
@Tomotori is correct. I am closing this issue as the tensorflow version issue has been solved by updating requirements.txt in #366 and more recently in #399.
