### ISSUE TITLE
Getting a synthesizer exception when running on a Mac

### ISSUE THREAD

**Issue by MustGet100** [CorentinJ/Real-Time-Voice-Cloning#310]
The tests say I'm good to go but when I try to record something, I keep getting the exception "Could not find any synthesizer weights under synthesizer/saved_models/.DS_Store/taco_pretrained".

I'm running this on a Mac so I'm wondering if that could be the source of any issues? I am using this fork so I don't think I should be getting this problem: https://github.com/shawwn/Real-Time-Voice-Cloning.

Is there perhaps something I forgot to add to the folder?

**Comment by mcfilms** [comment]
So you closed your issue. Were you successful in getting it to run on a Mac?

**Comment by woodrow73** [comment]
The test failed for me, however listed the same issue.  The fix for me was to properly copy over the pre-trained models, by copying over the saved_models folders without the folders they originally were contained within.

**Comment by blue-fish** [comment]
shawwn's fork is out of date now. Since then I got CPU support merged upstream in #366 and added a lot of other small enhancements that make it a lot more usable. I have a mac and Corentin's repo runs just fine on it.

It annoys me that the toolbox defaults to `.DS_Store` for synthesizer, which leads to that error. We should fix it to ignore hidden folders.

**Comment by woodrow73** [comment]
Took me the morning, but I'm happy to say I got it running.  Really want to thank you blue-fish, Corentin, and others for the contributions to this project, and making this masterpiece accessible.  After a little tinkering with audio and text input, I already have audio output that blew my socks off.  I've noticed a few hacks to control the output, like putting a period after every word if I want more word spacing, and also how the word choice (perhaps mostly at the start) changes the tone of the output - reflecting the training data.

I'm thinking of making an application that automatically gives voices to the characters in the text based game called AI Dungeon, I'm hype for that.

I have a 2 quick questions if I may - 1. do you recommend installing webrtcvad, and 2.  Do additional datasets permanently change the model, or can you just remove the datasets to nullify them?  Also if there's any interesting or memey datasets you recommend outside of train-clean-100, hit me up

**Comment by blue-fish** [comment]
@woodrow73 
1. For mac and linux, installing webrtcvad is a no-brainer, it's easy and fixes the synthesizer gaps (check the "enhance vocoder output" box in the toolbox). For windows I would only recommend it if preprocessing datasets for training.

2. No, anything you do inside the toolbox UI does not alter the model weights. You will know if you are running a training script, it is impossible to do by accident. If you need better voice quality try the single-speaker finetuning process in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-663308789. It's slow on mac due to lack of GPU support but that's what I used for my experiments, so it's possible if you're patient.

**Comment by woodrow73** [comment]
Thanks for the response, I am on windows, so for now I will settle for quick audio edits in audacity (I saw you call webrtcvad a nightmare earlier, so for me it'd probably be a nightmare inception haha)  I could also reinstall on an Ubuntu VM, but I don't think it's worth it to me.

Thanks for the link, your proposed tool to facilitate creating a custom dataset sounds very helpful - I'll definitely be playing around with integrating datasets, and possibly making a single speaker TTS model tomorrow if I can manage it (learning from scratch).  The p240_demotoolbox audio files gave a really nice peak into the next step of evolution for this tech!

**Comment by netman789** [comment]
This solved a big question for me as to why the structure of the pre-trained model for the synthesizer had a completely different format than that for the encoder or vocoder.

**Comment by lisaiceland** [comment]
Just tested this and I'm getting the same error as above. Any suggestions?
