### ISSUE TITLE
How to save audio voice clone recordings?

### ISSUE THREAD

**Issue by Haven-Net** [CorentinJ/Real-Time-Voice-Cloning#352]
My only issue is saving the recordings I've created to my pc.
Does anyone know a good way to save audio voice clone recordings once you are done?  
Please share your thoughts.

**Comment by stev199** [comment]
i'm having the same problem !
couldn't find a way to save the generated voice.

**Comment by hectoronevu** [comment]
> 
> 
> My only issue is saving the recordings I've created to my pc.
> Does anyone know a good way to save audio voice clone recordings once you are done?
> Please share your thoughts.

It's been several months since I last visited this project, so my knowledge might be incomplete.
If you look into synthesizer/audio.py, there are two save methods available, for simplicity, I used save_wav. 

To use it, I added its call inside toolbox/__init__.py at the end of the vocode method.

        # Plot it
        self.ui.draw_embed(embed, name, "generated")
        self.ui.draw_umap_projections(self.utterances)

        # Save it
        from os import getcwd
        from pathlib import Path
        from time import strftime
        from vocoder.audio import save_wav
        wav_name = f'output_{strftime("%m%d%Y_%H%M%S")}.wav'
        wav_file = str(Path(getcwd(), wav_name))
        save_wav(x=wav, path=wav_file)

So the idea is that after the vocoding is done, the output audio file is saved in the current working directory. I hope this helps!

**Comment by blue-fish** [comment]
This will be resolved by #402 once merged.

**Comment by blue-fish** [comment]
(#402 introduces a toolbox update that allows exporting generated wavs to a file.)

**Comment by blue-fish** [comment]
Closing this issue now that #402 is merged. Please pull the latest code for the toolbox enhancement that lets you replay and save wavs generated in the toolbox.
