### ISSUE TITLE
OpenSource and Legal work of cloning

### ISSUE THREAD

**Issue by Antoinemartl** [CorentinJ/Real-Time-Voice-Cloning#381]
Hi, I have two questions. I don't quite understand what the open source license of the project really means. I also wonder what you mean by "we cannot allow you to clone the voice of someone else without a bit of legal work". Thanks for replies. @CorentinJ

**Comment by CorentinJ** [comment]
The license is an [MIT license](https://choosealicense.com/licenses/mit/), meaning that you're free to do anything with it. 

The bit about legal work is purely related to Resemble.AI, and "we" thus stands for "my team and I at Resemble". Our work at Resemble.AI is independent from this project.

In the youtube video description I had invited people to clone their voice through Resemble.AI (under the free plan) rather than to use my repo, but I had omitted that at Resemble.AI we cannot allow anyone to clone anyone else's voice without proving that they own the rights to that voice. Hence the bit about legal work.

**Comment by Antoinemartl** [comment]
All right, thanks for the information.  I used your repo, can I clone someone's voice to my liking without their permission?  I reassure you, I just want to know a little more about the laws, it's a friend's voice, I have no bad intentions. @CorentinJ

**Comment by CorentinJ** [comment]
Well whatever you do the consequences won't be on me.
