### ISSUE TITLE
What versions of everything does one need to avoid errors during setup? 

### ISSUE THREAD

**Issue by deltabravozulu** [CorentinJ/Real-Time-Voice-Cloning#385]
Hi all, 

I'm on Ubuntu 20.04 with Python 3.7 in a conda env. I have a Nvidia GTX660 GPU installed. 

I'm currently rockin' torch 1.2, cuda-10-0, tensorflow 1.14.0, tensorflow-gpu 1.14.0, and torchvision 0.4.0, along with everything else in requirements.txt. I am using python 3.7. For the life of me, I can't figure out how to get demo_cli.py to not give the error a bunch of people get: 

```Your PyTorch installation is not configured to use CUDA. If you have a GPU ready for deep learning, ensure that the drivers are properly installed, and that your CUDA version matches your PyTorch installation. CPU-only inference is currently not supported.```

Could someone give me the lowdown on precisely what packages and version numbers I need to make this thing fire up?

**Comment by blue-fish** [comment]
If you just want to try it out, pull the latest updates from this repo. We added CPU support in the last week. Run demo_cli.py with the --cpu option.

You get the message because `torch.cuda.is_available()` evaluates to False. Try troubleshooting that. The pytorch you need correlates with your driver version, check it at the command line with `nvidia-smi`. I spent a few hours trying to get this to work with 20.04, then gave up and went back to 18.04 where the setup is much more straightforward.

Tensorflow-CUDA compatibility is another consideration. The latest version of this repo requires tensorflow==1.15, where the precompiled binaries only support CUDA 10.0. Recent Nvidia drivers provide CUDA >= 10.1 which would mean building tensorflow from source.

**Comment by deltabravozulu** [comment]
Sweet. Thanks blue-fish. I'll give this a try tomorrow. I didn't think about 20.04 breaking things specifically. I'll probably just use a VM and/or toss a live-usb or SSD in and see if 18.04 is easier.  

I ultimately succeeded in my initial setup, but only for a few seconds before I got posix path errors (e.g. TypeError: invalid file: PosixPath('/home/$USER/Github/rtvc/test.mp3'). If anyone else lands on this particular bug/issue ever, https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/235#issuecomment-626354257 fixed it, though the line may vary.

**Comment by blue-fish** [comment]
20.04 is very much bleeding edge for this project considering how many moving parts are involved.

That path bug was squashed in #371 . Still, I appreciate you taking the time to report it and share the fix. I understand you will not want to mess with your working 20.04 setup, but if you install on 18.04 consider pulling the latest.

**Comment by blue-fish** [comment]
Closing this issue as it appears to be resolved. @deltabravozulu Please reopen this issue if you continue to have additional questions.
