### ISSUE TITLE
Synthesizer training on LibriTTS

### ISSUE THREAD

**Issue by sagar-spkt** [CorentinJ/Real-Time-Voice-Cloning#42]
In your thesis paper, you mentioned you couldn't produce meaningful alignments on the LibriTTS dataset even though it is the cleaner version of the LibriSpeech. Could you please explain what might be the reasons for the model not learning the alignments? Also, what are the preprocessing steps you did during training synthesizer on LibriTTS? Did you use Montreal Forced Aligner on the LibriTTS too?

**Comment by CorentinJ** [comment]
Given that I was short for the deadline, I didn't give it much of chance. I tried it once and gave up when I saw the loss plateaued with no alignments. I don't know for sure why it didn't converge, and I didn't want to waste time looking into it. I think LibriTTS is worth a shot, and I would also recommend using a different synthesizer implementation than mine if you're going that way, because it is fairly poor right now. 

I think I hadn't yet implemented the splitting on sentences when trying out LibriTTS. Logmmse (the noise removal algorithm) also came later.

Note that my commits before going public are [available](https://github.com/CorentinJ/Real-Time-Voice-Cloning/commits/master?after=2e8ef14bf7865c7e3828219236bac3b098d07584+69). You should be able to find more answers there. 9692bea9320cb18b988472b1c9aa0d195326c6a0 is the one where I changed back from LibriTTS to LibriSpeech.

**Comment by blue-fish** [comment]
I'm going to deprecate this issue in favor of #413 . @sagar-spkt perhaps someone will give the answers you need over there.

**Comment by blue-fish** [comment]
@sagar-spkt You might find this interesting. @mbdash is training the synthesizer on LibriTTS with default hparams in #449. We did not create alignments, instead discarding long utterances per @CorentinJ 's suggestion https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/413#issuecomment-657382603 .
