### ISSUE TITLE
Train with different data sets

### ISSUE THREAD

**Issue by Tayal-S** [CorentinJ/Real-Time-Voice-Cloning#471]
HI 
I want to train with different dataset (dev Librispeech). But i am not able to preprocess this data. Could you please help me here

**Comment by blue-fish** [comment]
@Tayal-S Still training the encoder (#467)?

You will want to change this line to `librispeech_datasets["dev"]["clean"]`:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/785e5513b45daf6a83b86b0b459f1717033859cb/encoder/preprocess.py#L122

The available configurations are defined here:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/785e5513b45daf6a83b86b0b459f1717033859cb/encoder/config.py#L1-L14

The software is not too user-friendly so you will need to edit the code yourself to make it do new things. When the preprocessing is working please close out the issues you have opened.

**Comment by Tayal-S** [comment]
HI 

Thanks for the quick reply. When i dig into the code , i found it. i am very new to Speech Algorithm.
But i have an another query regarding mixed data:
If Text input is in German but output is needed in English. Could you please help, which data needs to be trained in three sets: Encoder, Synthesizer and Vocoder.

**Comment by blue-fish** [comment]
> If Text input is in German but output is needed in English.
Perform machine translation on your German text to convert it to English. Then use the toolbox as normal with the English text as input. We already have [pretrained models](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models), there is no need to train your own based on what you have told me so far.

I apologize but I need to close this issue because your query is outside the scope of what we can provide support for here. Issues are mainly for bug reports and feature requests. Help for toolbox installation and use is only provided if we have time for it. We cannot consult or assist with personal projects.

Mozilla TTS has an online community where you can ask your question. https://discourse.mozilla.org/c/tts/285
