### ISSUE TITLE
Error: Model Files not found

### ISSUE THREAD

**Issue by malewpro** [CorentinJ/Real-Time-Voice-Cloning#494]
Might be a silly issue but I'm somewhat new to this. I've managed to get all the repositories running properly but I've run into a roadblock where my toolbox doesn't recognize the pre-trained models I've downloaded and placed into the repo's root folder. I'm not sure if I've placed them in the wrong location or if I'm doing something else incorrectly.

I've downloaded the model .zip and placed the "saved_models" from the zip's encoder folder inside the root's encoder folder. I've done the same with the synthesizer and vocoder. However, the toolbox never seems to recognize that they are there. Should I be organizing the files differently?

**Comment by blue-fish** [comment]
@malewpro Please make sure the files can be found at the locations that the toolbox is expecting.
```
enc_model_fpath: encoder\saved_models\pretrained.pt
syn_model_dir: synthesizer\saved_models\logs-pretrained
voc_model_fpath: vocoder\saved_models\pretrained\pretrained.pt
```

If the files are in the correct location then make sure you are running python out of the Real-Time-Voice-Cloning folder since it is evaluating those paths relative to the location from which python is launched.

We really need to improve the error message, as #463, #476, #482, and now this issue all had the same problem. Perhaps also print out what files are expected where.

Before I added this check in #416 we got a lot of issues opened by people who never downloaded the pretrained models.

**Comment by malewpro** [comment]
Yeah, my inexperience is really showing here. Everything was saved in the right place but I was running python out of the wrong folder. Once I corrected this it launched perfectly. Thanks so much and sorry for the repeat issue!
