### ISSUE TITLE
Recommendations needed

### ISSUE THREAD

**Issue by TorIPi0** [CorentinJ/Real-Time-Voice-Cloning#511]
Hi. I'm a developer working on an art project that specifically needs the ability to clone a voice in real time from a short sample (less than 20 seconds), and output text immidately. I see that development on this repo is stopped, and I'd like to know if there are any forks out there that are somewhat easier to set up? (Not reliant on obsolete versions of software, etc).
I'd also be willing to pay for this, but from what I can see on the Resemble.AI site this particular service isn't really something your company offers?

Thanks in advance

**Comment by mbdash** [comment]
see #437

**Comment by blue-fish** [comment]
This project is not affiliated with Resemble.AI although the creator is.

The current repo is not too hard to set up if you can live with CPU-based inference. The slow part is the vocoder and since you need this to perform in real time, you options are getting GPU support for pytorch (relatively easy), or swapping out the vocoder for a faster one (hard if you're new to this, and merely tedious if you're not).

My [pytorch fork](https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/447_pytorch_synthesizer) (currently going through the PR process) does not require an old version of tensorflow. We still have some catch-up for compatibility with the latest librosa and matplotlib. However, there is no good pretrained model for the torch-based synthesizer at this time and if you want to wait for it, it will be a few weeks.

**Comment by TorIPi0** [comment]
A few weeks will be more than good enough, thank you blue-fish :-) And thanks for the recommendation mbdash.

**Comment by mbdash** [comment]
Here is some partial documentation I have written.
It is missing the Nvidia drivers setup instruction which I hope I will be allowed to add to this project's WIKI.


# On Ubuntu 20.04

## Create a Conda workspace
```
conda deactivate

conda create --name prj_rtvc_py373 python=3.7.3
conda activate prj_rtvc_py373 
```

## Create edited requirement file
Open requirements.txt and edit the file to match the content below.
Save as requirements_conda_anaconda.txt
```
tensorflow==1.15
umap-learn
visdom
librosa>=0.5.1
matplotlib>=2.0.2
numpy>=1.14.0
scipy>=1.0.0
tqdm
python-sounddevice
pySoundFile
Unidecode
inflect
# PyQt5
multiprocess
numba==0.48
```

## Install packages
```
conda install -c conda-forge pytorch=1.2.0 torchvision=0.4.0
conda install ffmpeg

conda install -c conda-forge --file requirements_conda_anaconda.txt

# requirements_gpu.txt will not install
# conda install --file requirements_gpu.txt
pip install webrtcvad
conda install tensorflow-gpu=1.15
```

**Comment by mbdash** [comment]
See the new wiki
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki
