### ISSUE TITLE
Add volume Bar

### ISSUE THREAD

**Issue by ranshaa05** [CorentinJ/Real-Time-Voice-Cloning#522]
some recordings have low volume so the output can be sometimes really quiet. how about we add a volume bar so we can make the output louder/quieter?

**Comment by blue-fish** [comment]
@ranshaa05 Interesting suggestion. Have you tried selecting the "enhance vocoder output" button on the toolbox UI? That will normalize the volume among other things.

**Comment by ranshaa05** [comment]
> @ranshaa05 Interesting suggestion. Have you tried selecting the "enhance vocoder output" button on the toolbox UI? We added that to trim silences, but it also normalizes the volume of the generated wav.

It doesn't work for me at the moment (looks like some cudnn shannanigans) but i do remember it making the output a bit louder, but it certainly wasnt perfect. Even the "normalize" option in audacity doesnt work 100% of the time. That's why im suggesting a simple volume bar to have a bit more control over the actual volume.

**Comment by blue-fish** [comment]
The toolbox is not intended to be a full-featured text-to-speech solution, but I can understand the desire for this capability since the output volume is not consistent for different speakers.

Are you able to develop this feature and submit a pull request? Or are you asking for someone else to take on this task?

**Comment by ranshaa05** [comment]
> The toolbox is not intended to be a full-featured text-to-speech solution, but I can understand the desire for this capability since the output volume is not consistent for different speakers.
> 
> Are you able to develop this feature and submit a pull request? Or are you asking for someone else to take on this task?

Unfortunately i am not skilled enough in python to develop this feature, so yeah, im asking for somebody else to do it.

**Comment by blue-fish** [comment]
@ranshaa05 I'll gladly work this when the pytorch PR, bugs and dependency issues are complete. Or possibly earlier if I have a free moment.

Since it could be a while I'll flag this as an issue for others to help out.

**Comment by ranshaa05** [comment]
> @ranshaa05 I'll gladly work this when the pytorch PR, bugs and dependency issues are complete. Or possibly earlier if I have a free moment.
> 
> Since it could be a while I'll flag this as an issue for others to help out.

thanks! :)

**Comment by blue-fish** [comment]
@ranshaa05 Finally got around to this feature request. Please see my [`522_volume_bar`](https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/522_volume_bar) branch for the code.

The volume bar replaces the "Enhance vocoder output" box, which is unnecessary since our newer models do not synthesize silence. After the change, the toolbox UI looks like this.

![image](https://user-images.githubusercontent.com/67130644/110234411-306a1f00-7edf-11eb-925e-9ba03373454e.png)

**Comment by ranshaa05** [comment]
> @ranshaa05 Finally got around to this feature request. Please see my [`522_volume_bar`](https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/522_volume_bar) branch for the code.
> 
> The volume bar replaces the "Enhance vocoder output" box, which is unnecessary since our newer models do not synthesize silence. After the change, the toolbox UI looks like this.
> 
> ![image](https://user-images.githubusercontent.com/67130644/110234411-306a1f00-7edf-11eb-925e-9ba03373454e.png)

nice! thanks :)

**Comment by blue-fish** [comment]
Thanks for the suggestion @ranshaa05 . However, I'm not going to submit a pull request this unless more people ask for it. I hope the feature is working well for you.
