### ISSUE TITLE
Hard Install and poor install documentation

### ISSUE THREAD

**Issue by Nvrgp22** [CorentinJ/Real-Time-Voice-Cloning#539]
I have been working on a project of mine, and i needed a voice cloner. This is the only one on the free internet, and i do think that you are have been doing an amazing job. To run your code, i would need to downloade more than 8 applications, and if i would, even then i still coudn't run the software becouse its "written to be able to run on nvidea gpu-s only" ~ by a lot of sources.
So, all i'm asking for, is to port it to an executable. 

Also, there is this asshole selling your project for 999.99$ : 
https://realtimevoicecloning.com/

**Comment by blue-fish** [comment]
Please see this statement from repo owner: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/543#issuecomment-705988630 You're not missing out on much: the voice quality is really bad, though it is something I am working to improve.

Since an executable is highly requested, I am leaving #267 open with the hope that someone from the community will compile it. You might be interested to know that the code no longer requires a GPU to run. It's an enhancement that other community members and I have worked on.
