### ISSUE TITLE
Training net on just one voice?

### ISSUE THREAD

**Issue by holisticmaniac** [CorentinJ/Real-Time-Voice-Cloning#547]
Hi,

I'd like to train the network just to clone one voice. Can someone give me an advice on how to do this?

**Comment by blue-fish** [comment]
Please see #437 for information on how to do this. You should also refer to the training documentation here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training

**Comment by holisticmaniac** [comment]
Thank you. I tried to follow the steps, but something does not seem to work properly. I never used the tool before and am a python beginner, so I might have done something wrong :(. I am using windows 10. 

1. based on [this](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538) comment, I prepared my audio and text files accordingly. I did not have webrtc
2. I used `python synthesizer_preprocess_audio.py datasets_root --datasets_name LibriTTS --subfolders train-clean-100 --no_alignments ` to preprocess the audio files, which seemed to work.
3. I then created the embeddings as describe in the [Training wiki ](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training): `python synthesizer_preprocess_embeds.py <datasets_root>/SV2TTS/synthesizer`
4. This resulted in a SV2TTS\synthesizer\audio\audio-utterance-001.npy, SV2TTS\synthesizer\embeds\embed-utterance-001.npy and SV2TTS\synthesizer\mels\mel-utterance-001.npy files for each utterance which should be fine.
5. I then started training the synthesizer with  `synthesizer_train.py my_run <datasets_root>\SV2TTS\synthesizer --checkpoint_interval 50 `
6. The plots of predicted and target spectrogram looked reasonably well and the wav files already sounded similar to the target voice, so I aborted after 300 steps 
7. ![step-300-mel-spectrogram](https://user-images.githubusercontent.com/72363021/95448718-0e866380-0964-11eb-9abe-6654c53c4a00.png)
8. I then tried to generate data for the vocoder with `python vocoder_preprocess.py <dataset_dir> --model_dir synthesizer\saved_models\logs-my_run --no_trim`

I got this message:

>  Loaded metadata for 104 examples (0.12 hours)
> Starting Synthesis
> 0it [00:00, ?it/s]

and no training data was created in <datasets_dir>\SV2TTS\vocoder\mels_gta and the synthesized.txt is also empty. 

At this point I'm stuck and do not know how to further proceed and find the problem. 

I also get a lot of warning about deprecated functions in tensorflow and wonder if I have the correct version of SV2TTs or my setup is wrong? I did it based on [this tutorial](https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/)

**Comment by blue-fish** [comment]
Wow, you got really far considering this is your first time using the repo. It may not be necessary to finetune the vocoder model. Try using your finetuned synthesizer model in the toolbox. If it doesn't match your expectations then train a few more steps or add more training data.

Do not fret about the tensorflow warnings, it is normal. (We had an open issue to remove the warnings #444 but no one wanted to work on it...)  If you have the time and a GPU, it would be helpful to actually go through the motions of training a synthesizer and vocoder from scratch so you have some context and experience.

**Comment by blue-fish** [comment]
Make sure you downloaded the [pretrained models](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models) and are continuing the training of the synthesizer which is already at 278,000 steps. To do this, make the first argument to synthesizer_train.py XXXX, which represents the logs-XXXX folder where the existing checkpoint is located. So instead of `my_run` you can call it `pretrained`. Although the output might sound intelligible at 300 steps when training from scratch, that's because it uses teacher forcing and uses the ground truth as input to the decoder. That is not available during inference.

**Comment by holisticmaniac** [comment]
Thank you, I tried to read everything I could find, but wasn't sure if I got it right :). 

I trained a few additional steps since the 300 steps were indeed not enough and the spectrograms were all noisy. Now I have 1200 training steps and made another test. For this, I used my my_run synthesizer with the pretrained encoder and vocoder. Does not reproduce the text very well but the voice is already clearly hearable. So I guess, more training is required ;). 

I have two additional questions if you don't mind: 

1. I used a very rough cut dataset for now. That is, in some samples, words are cut off and the end. And I have done the transcripts automatically, so there might be some errors in it the text-to-speech translation. So my question is, how robust the net is against such noise in your experience? In other words, is it important to input an absolutely clean dataset? 
2. Do you have any idea, why the vocoder training does not work? 

As for your comment [here  ](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/547#issuecomment-705840054), was it with regard to training a new model from scratch? That might take a long time though since I do have an AMD graphics card, so I can't use CUDA, but is there an alternative I do not know of and which I can use for AMD?  

I have AMD Radeon Vega 8 Graphics and AMD Ryzen 3 2200G CPU.

**Comment by blue-fish** [comment]
1. You can have a few errors in your transcripts but the overall error rate needs to be very low.
2. Don't bother with it. The pretrained vocoder is already quite good and does not benefit that much from additional training.
3. If you have alignment files, the synthesizer preprocess script can do it for you automatically. You can generate alignments with [Montreal Forced Aligner] or any of the tools on [this list](https://github.com/pettarin/forced-alignment-tools). Be warned: the setup is about as hard as this repo, if not harder.

It is possible to do machine learning on AMD with ROCm , but if you value your time just find a way to use CUDA. You won't get much acceleration from a Vega 8. If needed, rent a GPU in the cloud. See #398.

Regarding that comment, you need to realize that it's possible to take Corentin's pretrained synth model and continue the training where it left off. By pointing the training script to the checkpoint (`python synthesizer_train.py pretrained ...`) it will load the weights from the pretrained model, and update them as training progresses.

Do not train your dataset from scratch, it will not yield a usable model because the dataset is too small to generalize.

**Comment by holisticmaniac** [comment]
Thanks for the help, I will try to play around a bit and train and test a few models :).

**Comment by Jindalee-AUS** [comment]
Hi Guys
I have been following several threads for a couple of weeks. I’m making a animated movie I have a couple of hundred utterances (but can get more) from the voice over actors, rather than getting them to rerecord every time I make a change to the script. With that in mind I have been trying to run vocoder_preprocess.py before running the vocoder_train.py.
1.	I’m new to python, but have managed to install and run the demo_cli.py and the demo_toolbox.py
2.	Am I wasting my time trying to get a voice that sounds a bit like the original this way?
3.	Can’t get past the first hurdle. I can’t get my head around the folder structure, I have run the –h and read all that I think I understand all that the dataset root should have folders for LibriSpeech/TTS and VoxCeleb1/VoxCeleb2 datasets, which I have but what is the code expecting to find in them? From the down loaded pertained the readme.txt shows a structure with 4 txt files plus the train-clean-100/ and its sub folders. 
demo_toolbox.py -d C:\Users\Administrator\anaconda3 this works for the demo_toolbox  So what is wrong with vocoder_preprocess.py -d C:\Users\Administrator\anaconda3
(base) C:\Users\Administrator\anaconda3>encoder_preprocess.py
usage: encoder_preprocess.py [-h] [-o OUT_DIR] [-d DATASETS] [-s] [--no_trim]
                             datasets_root
encoder_preprocess.py: error: the following arguments are required: datasets_root

**Comment by blue-fish** [comment]
> Am I wasting my time trying to get a voice that sounds a bit like the original this way?

@Jindalee-AUS Because the synthesizer is trained on audiobook data, the output voice sounds just like that. There is no control of emotion, only the randomness of the synthesizer. With all the problems of the current synth model, it's more of a novelty and not suited for production use. If you must try it, set your expectations very low.

Being new to python you will likely find it quite frustrating, but don't let that discourage you if you're determined and willing to put in many many hours of work. This being said, I'm going to allocate my limited time to development and not provide consultation on side projects anymore, so I cannot really help you further. You can see my work in #437 which includes tutorials and single-speaker mini-datasets that have been preprocessed.

**Comment by Jindalee-AUS** [comment]
Many thanks blue-fish
I have taken that on board and have read your work in #437, I will be referring back to that often. I’m enjoying playing with this Tool Box. 
I have just one final question is it not possible to save the output from “demo_toolbox.py” maybe I’m missing something?
