### ISSUE TITLE
Why the generated voice sounds so unreal?

### ISSUE THREAD

**Issue by chris795** [CorentinJ/Real-Time-Voice-Cloning#564]
I try this on my GPU clound and use my own voice (20 minutes length) as a sample, but the generated voice sound too far from my real voice.

**Comment by blue-fish** [comment]
Please read through #411 for some clues to why this is the case. Can also read #41 and #364. Some voices will clone better than others due to their representation by the speaker encoder and the training data used.

If you want better similarity with your own voice, you can generate your own training data and finetune a single-speaker model. See #437 for information on how to do it (no support available).
