### ISSUE TITLE
Compatibility with Pytorch 1.8 and CUDA 11

### ISSUE THREAD

**Issue by rallandr** [CorentinJ/Real-Time-Voice-Cloning#586]
Hi, 

In order to take advantage of Nvidia Amper architecture, I was wondering how one could make the synthesizer andd vocoder training program use Pitorch 1.8 and CUDA 11.

Any lead on the procedure to follow would be very helpfull. 
Thank you

**Comment by blue-fish** [comment]
Because tensorflow 1.x only supports CUDA 10, you'll need a new synthesizer model. I have a pytorch-only synthesizer in #472 ([pretrained model](https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/472#issuecomment-695206377)). No modifications should be needed for vocoder training.

I don't expect bugs with pytorch 1.8 but please report them if they are encountered.

**Comment by rallandr** [comment]
Thanks @blue-fish 

However I keep running in a CUDNN error while trying to train the vocoder. 
"RuntimeError: Unable to find a valid cuDNN algorithm to run convolution"

I guess this is because CUDA 11 works with cudnn 8 and not cudnn7...

**Comment by rallandr** [comment]
Thanks @blue-fish

However I keep running in a CUDNN error while trying to train the vocoder.
"RuntimeError: Unable to find a valid cuDNN algorithm to run convolution" and it doesn't start the training.

With smaller batch size it starts but stops after few seconds with the following cudnn error : 
"{| Epoch: 1 (11/52) | Loss: 4.1256 | 0.8 steps/s | Step: 436k | }Traceback (most recent call last):
  File "vocoder_train.py", line 55, in <module>
    train(**vars(args))
  File "D:\dfvoc\Real-Time-Voice-Cloning-master\vocoder\train.py", line 106, in train
    running_loss += loss.item()
RuntimeError: CUDA error: unspecified launch failure"


I guess this is because CUDA 11 works with cudnn 8 and not cudnn7...
