### ISSUE TITLE
hello i have issues starting the program 

### ISSUE THREAD

**Issue by Elementalix** [CorentinJ/Real-Time-Voice-Cloning#591]
Hello i have issues starting the program i got this issue :
ImportError: cannot import name '_imaging'
Any idea ?

**Comment by blue-fish** [comment]
Sorry but we no longer use the issues board for general technical support questions, for reasons similar to [`tensorflow/ISSUES.md`](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md). If you have evidence that this is caused by a bug in the repo code, please share and we'll troubleshoot.
