### ISSUE TITLE
Another problem...

### ISSUE THREAD

**Issue by notluke27** [CorentinJ/Real-Time-Voice-Cloning#631]
![Captura de Tela 2021-01-18 às 16 18 37](https://user-images.githubusercontent.com/77593871/104955321-d2be5980-59a8-11eb-8a7c-b3f2a03a0b21.png)
There is a gap between words... and also a weird noise
The audio: https://drive.google.com/file/d/1Qm2Y_zt2bJJqZVGsB70yA1K0Judkn4Mp/view?usp=sharing

**Comment by blue-fish** [comment]
The gaps are also due to long pauses between words and sentences in the training data. It's improved with my alternative synthesizer model in #538.

Weird noises are an artifact of the training data, which has a lot of mic bumps. It may be slightly better with my 002 vocoder model in #400 . Those go away when you vocode with Griffin-Lim, but you get different quality problems.

**Comment by xuexidi** [comment]
> The gaps are also due to long pauses between words and sentences in the training data. It's improved with my alternative synthesizer model in #538.
> 
> Weird noises are an artifact of the training data, which has a lot of mic bumps. It may be slightly better with my 002 vocoder model in #400 . Those go away when you vocode with Griffin-Lim, but you get different quality problems.

@blue-fish 
**Hi，thanks for your pretrained models! It performed perfect!**

**I would like to ask you some questions:**
you mentioned: "The gaps are also due to long pauses between words and sentences in the training data. "
Is that means the only way to reduce the "gaps" is to clean up the sentences with " long pauses" in traning data?  is there any other tricks in "trainig" or in "inference"？

Looking forward to your reply. Thank you!

**Comment by blue-fish** [comment]
@xuexidi If gaps are a problem, you can also remove them from synthesized utterances with voice activation detection (VAD). That's what the "Enhance vocoder output" button does. I'm not aware of any other tricks at this time. Corentin has these suggestions for preprocessing and training:
1. https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/364#issuecomment-653996443
2. https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/364#issuecomment-660075042

**Comment by xuexidi** [comment]
> @xuexidi If gaps are a problem, you can also remove them from synthesized utterances with voice activation detection (VAD). That's what the "Enhance vocoder output" button does. I'm not aware of any other tricks at this time. Corentin has these suggestions for preprocessing and training:
> 
> 1. [#364 (comment)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/364#issuecomment-653996443)
> 2. [#364 (comment)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/364#issuecomment-660075042)

@blue-fish 
I got it!
Thanks a lot, it seems the only way to reduce "gaps"  is to improve the quality of training speech data.

**Comment by bigdog3604** [comment]
> @xuexidi If gaps are a problem, you can also remove them from synthesized utterances with voice activation detection (VAD). That's what the "Enhance vocoder output" button does. I'm not aware of any other tricks at this time. Corentin has these suggestions for preprocessing and training:
> 
> 1. [#364 (comment)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/364#issuecomment-653996443)
> 2. [#364 (comment)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/364#issuecomment-660075042)

@blue-fish I've been beating my head against the wall for 2 days trying to get the toolbox to work.  Today, I finally got the GUI to launch...but here's my problem:  GUI launches, I can import a wav file into the toolbox but, then, the system attempts to load the encoder from encoder\saved_models\pretrained.pt and just sits there until I finally exit out of the program.  I've verified pretrained.pt is at C:Real-Time-Voice-Cloning-master/encoder/saved_models.  Any help would greatly be appreciated!
