### ISSUE TITLE
Qbasic timer error

### ISSUE THREAD

**Issue by clonereal** [CorentinJ/Real-Time-Voice-Cloning#658]
GUI is opening properly but not working. Every time I press any button, it show following in Terminal:

QBasicTimer::start: QBasicTimer can only be used with threads started with Qthread

I am using Ubuntu 20.04.

**Comment by blue-fish** [comment]
Unable to reproduce issue on Ubuntu 20.04.
For reference, this is how I setup the toolbox from a fresh install: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/615#issuecomment-740270185
(It should work with the preinstalled Python 3.8 but I haven't had time to update and retest)

I think the issue is with your system configuration, but let us know if you have evidence that it's our code.

**Comment by clonereal** [comment]
It is working now. Issue was with python 3.9, It is working fine with python 3.8 

Thanks..
