### ISSUE TITLE
Bug in inference code

### ISSUE THREAD

**Issue by MaratZakirov** [CorentinJ/Real-Time-Voice-Cloning#681]
synthesizer/inference.py:

len(inputs) returns you 1 (if demo_cli.py used), but inputs is a list which potentially can have any size. So batched_inputs is not "batched" in any sense.

       # Batch inputs
        batched_inputs = [inputs[i:i+hparams.synthesis_batch_size]
                             for i in range(0, len(inputs), hparams.synthesis_batch_size)]
        batched_embeds = [embeddings[i:i+hparams.synthesis_batch_size]
                             for i in range(0, len(embeddings), hparams.synthesis_batch_size)]

**Comment by MaratZakirov** [comment]
Also there should be some way to keep states and continue to inference for new batches to ensure connectivity of the speech.

**Comment by blue-fish** [comment]
> synthesizer/inference.py:
>
> len(inputs) returns you 1 (if demo_cli.py used), but inputs is a list which potentially can have any size. So batched_inputs is not "batched" in any sense.

I don't quite understand the concern. We use batching in the toolbox. There is also an example of how to use batching in demo_cli.py. It's appropriate to call it "batched" in synthesizer/inference.py.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/toolbox/__init__.py#L224-L229

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/demo_cli.py#L104-L109

> Also there should be some way to keep states and continue to inference for new batches to ensure connectivity of the speech.

With batching, it's hard because everything is processed in parallel. One way to get around this is to synthesize segments with overlap and then blend them together. See the below figure from Corentin's thesis.

Synthesizing one sentence at a time is good enough for me, so I find this unnecessary. For better flow between sentences, you should improve or remove the attention mechanism. Then there would be no limit on the length of the text input. These papers can be used as a starting point if you want to pursue this.

* https://arxiv.org/pdf/1910.10288.pdf (Battenberg et. al, "Location-Relative Attention Mechanisms for Robust Long-Form Speech Synthesis")
* https://arxiv.org/pdf/2010.04301 (Shen et. al, "Non-Attentive Tacotron: Robust and Controllable Neural TTS Synthesis Including Unsupervised Duration Modeling")

![image](https://user-images.githubusercontent.com/67130644/109261945-8ccd9000-77b5-11eb-895b-5c02151bd94f.png)

**Comment by MaratZakirov** [comment]
Off-topic but I found that after long phrases (> 128 symbols) RNN (I guess) get some UNremovable trash in its state and the speaker starts to say some indistinguishable noise. So with this model actually I have to split texts to relatively small portions of texts.

**Comment by blue-fish** [comment]
Those problems in inference are caused by failures of the attention mechanism. We currently use Location-Sensitive Attention. There is a comparison of attention methods in 1910.10288 and LSA is one of the worse ones.
