### ISSUE TITLE
Error "list index out of range" in  synthesizer_preprocess

### ISSUE THREAD

**Issue by ks-sav** [CorentinJ/Real-Time-Voice-Cloning#749]
Before that, I processed other datasets and everything was OK, but something strange is happening with this: (the folders are located in the same way as in LibriTTS)

![image](https://user-images.githubusercontent.com/52282778/116607434-a799bd80-a93a-11eb-986c-54f5fce82ef9.png)

**Comment by blue-fish** [comment]
This is happening because the resulting list is empty. Your audios might be too short or long.

**Comment by Highpressure** [comment]
your first command already failed... for me it was including the directory before the files are in place as it seems to not parse multi directory depth...

python synthesizer_preprocess_audio.py E:\DeepFakes\cleanRTVC --subfolders de_DE\**by_book\male\karlsson\** --dataset "" --no_alignments --no_trim -n 4

this did work on my machine fine

and then I ran

python synthesizer_preprocess_embeds.py E:\DeepFakes\cleanRTVC\SV2TTS\synthesizer

while here you used instead of \ also forward slash / which is for linux..

in case you still wonder, or anyone else is in trouble like me the last days
