### ISSUE TITLE
Is there any difference between Pytorch and tensorflow outputs?

### ISSUE THREAD

**Issue by Sba-Stuff** [CorentinJ/Real-Time-Voice-Cloning#750]
Although my question might look idiotic, I apologize in advance to ask. But, I want to know either there is any difference in outputs generated with PyTorch and Tensorflow or not. I have tried and used Tensorflow implementation. I just want to know if there is any difference using Pytorch version in generated outputs.

**Comment by blue-fish** [comment]
Yes there will be because the model architectures are different. The old Tensorflow is Tacotron 2 ([1712.05884](https://arxiv.org/pdf/1712.05884.pdf)) and the new PyTorch is Tacotron 1 ([1703.10135](https://arxiv.org/pdf/1703.10135.pdf)).

Pytorch and Tensorflow use the same building blocks, so that is not the source of any difference you may notice.

**Comment by Sba-Stuff** [comment]
Thank You.
