### ISSUE TITLE
Saving the trained model

### ISSUE THREAD

**Issue by Anas-eladili** [CorentinJ/Real-Time-Voice-Cloning#785]
After training on few audios input i want to save the trained model so that i can use it again when i need it whithout having to redo all the application again. How can i save these models ?  Thank you

**Comment by pilnyjakub** [comment]
The models are saved automatically, you can change the frequency in encoder_train.py/synthesizer_train.py or by passing the parrameters.

**Comment by erfanlashkari** [comment]
🐲

**Comment by erfanlashkari** [comment]
too day

**Comment by Itlink75** [comment]
Hi , sorry for asking any further .pilnyjakub said they are saved automatically . As far as i understood, it is not possible to retrieve them with the main GUI but may i know how are those models called (file type or any name) , in order for me to be able to retrieve them and possibly reuse them (how?) . thanx a lot

**Comment by pilnyjakub** [comment]
Models are trained on multiple voices. They can then be used on any voice. When they are used, they are unpredictable unless you set the random seed to specific value. There is no "saving" at this stage (already using the model).

**Comment by blue-fish** [comment]
Loading an audio in the toolbox does not train or alter the model in any way. It just changes the speaker embedding (an array of size (256,)) input to the synthesizer. Only the embedding from the last loaded audio is used during generation. Due to dropout, the synthesizer output is never the same for a given set of inputs (speaker embedding + text) **unless** the "random seed" parameter is set to force deterministic generation.
