### ISSUE TITLE
Can we get a handholding tutorial?

### ISSUE THREAD

**Issue by Jetical** [CorentinJ/Real-Time-Voice-Cloning#821]
Granted some level of code implementation is needed to run this repo, i am a beginner, as are a lot of people, can we have a link or two here to a conistantly updated video documenting how to install and run this program? whats offered is meant for tech heads and code monkies. granted i am taking the time to learn everything to install this repo, i do think it is a bit much going from zero to a hundred, especially in my case for comical vids to be.

**Comment by Jetical** [comment]
I managed to boot it up, however all my training attempts from audio clips, make my voices come out out of breath, terrified and scratchy, the more i synthesize, the weirder the voices become, so yeah, i'm somewhere at least lol

**Comment by pilnyjakub** [comment]
Not sure what dataset you're using. But with default batch size, you should hear understable sentences at around 20k steps in wavs directory.

**Comment by Jetical** [comment]
Yeah, not gonna lie don't know what that means, i just jumped head first into this without a parachute and tried cloning "big the cat" voice, instead i get some out of breath creeper reading my synthesized text, the clip isn 5 seconds long(i can make it that short if need be) , i thought this program of cloning worked better the more times the voice was synthesized. Anywho if can be pointed in the right direction im certain i can make a fix. My skill is low when it comes to running programs like these, but my bag is full of comedic gold to come. and i have patience to learn. so that being said, if your willing to help or googlearn me, what do you mean, dataset, batch size,and  what do you mean by "steps?"

**Comment by Ratteler** [comment]
Honestly, I'm not even sure if I'm following the right thing.
"Real Time" isn't a necessity for me. I'm looking for a FOSS implementation of Adobe's project VoCo because I run Linux as my main OS now, and Adobe has implemented a pricing structure I find offensive.
I already do decent imitations of some people. As an Blender animator, I can do anything visually. The place I am weakest is in needing to hire voice talent. Otherwise I'm a one man movie studio.

I would love to see this as a feature on Tenacity (Audacity fork with no telemetry).
Maybe a YouTube channel for us artists would help get some support.
I would Patreon a Foss VoCo in a heartbeat.

**Comment by pilnyjakub** [comment]
@Jetical You mentioned training, that's why I thought you would need help with it. Make sure that the audio you feed into the program is good as it can be, it doesn't have to be necessarily 5 second long (or short) and you don't really need more than one audio. The pretrained models were trained mainly on audiobooks, that's why your "Big the Cat" audio won't work as expected. Text you're trying to synthesize should be around 40 - 50 characters per sentence.

**Comment by blue-fish** [comment]
@justinjohn0306 has a video tutorial: https://www.youtube.com/watch?v=vHSulnOxfGo

**Comment by Jetical** [comment]
Thank you
