### ISSUE TITLE
Does quality depend on batch size? I only have 6 gb of memory, but I want results like in paper.

### ISSUE THREAD

**Issue by fancat-programer** [CorentinJ/Real-Time-Voice-Cloning#860]

**Comment by blue-fish** [comment]
Can't answer this question because we still can't get results as good as the paper.

Here are my results, which should still represent the state of the art for open source SV2TTS.
https://blue-fish.github.io/experiments

**Comment by fancat-programer** [comment]
Is it possible that the google results are fake or this repo does not fully match the paper or do we need a different dataset?

**Comment by blue-fish** [comment]
Based on my exploration, I believe their results are real. We need a better dataset for the encoder. Differences in model structure might also exist since theirs is closed source. To match the paper, we should start by reproducing the results in [1703.10135](https://google.github.io/tacotron/publications/tacotron/index.html) and [1712.05884](https://google.github.io/tacotron/publications/tacotron2/index.html) (the Tacotron 1 and 2 papers). After validating our synthesizer and vocoder implementations, we can return to [1806.04558](https://google.github.io/tacotron/publications/speaker_adaptation/index.html) to match the encoder.

**Comment by fancat-programer** [comment]
For my language there is a huge dataset of speech of different quality (from noisy recordings to ~ studio quality) in it 20,000 hours of speech and more than 10,000 speakers, can I get paper quality with it?

**Comment by blue-fish** [comment]
As I said earlier, we don't understand what it takes to get paper quality. You'll have to answer your question by training a model.

**Comment by fancat-programer** [comment]
Okay, as soon as the model is trained I will post the results and the model.

**Comment by fancat-programer** [comment]
But does batch_size still affect quality?

**Comment by blue-fish** [comment]
I have trained usable synthesizer and vocoder models with very small batch sizes (=2). Due to limited VRAM, I haven't conducted experiments with large batch sizes, so I can't tell you if quality would improve.
