### ISSUE TITLE
I used to have better quality outputs

### ISSUE THREAD

**Issue by francogrex** [CorentinJ/Real-Time-Voice-Cloning#867]
I had tried out this two years ago, and again now. Same PC, the differences I can think of are: a newer version of python, newer version of this repo and dependencies, including removal of tensorflow (which was a pain to get a working version). But the outputs I get now are of significantly less quality than what I used to have (I always started from a same wav voice to clone (an Obama speech).

**Comment by blue-fish** [comment]
The old version used Tacotron 2 and a different pretrained model. We lost that during the PyTorch conversion in #472. The new model will perform better on some voices, worse on others. You can compare audio samples on [my website](https://blue-fish.github.io/experiments/): RTVC-2 for the old model, and RTVC-7 for the new.

#### If you want to try the old version again:

Here is a link to the last Tensorflow version: https://github.com/CorentinJ/Real-Time-Voice-Cloning/tree/5425557efe30863267f805851f918124191e0be0

And the instructions to install it. (Click the "edited" dropdown and select the original Jan 28 version. Otherwise the new instructions will not work!) https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

**Comment by blue-fish** [comment]
> For what reason, when switching from tensorflow to pytorch, the architecture was changed to takotron1?

I provided the reasons here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/447#issuecomment-664710815

The synthesizer code is a lot cleaner now, which makes it a lot easier to update the model architecture if desired. I have tried both Taco1 and Taco2, and as I said in #472: "Tacotron 1 learns faster than Tacotron 2. Training time per step is about the same, but the model is usable in fewer steps. Voice quality is similar. Attention is more robust in Taco2."

**Comment by e0xextazy** [comment]
> > For what reason, when switching from tensorflow to pytorch, the architecture was changed to takotron1?
> 
> I provided the reasons here: [#447 (comment)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/447#issuecomment-664710815)
> 
> The synthesizer code is a lot cleaner now, which makes it a lot easier to update the model architecture if desired. I have tried both Taco1 and Taco2, and as I said in #472: "Tacotron 1 learns faster than Tacotron 2. Training time per step is about the same, but the model is usable in fewer steps. Voice quality is similar. Attention is more robust in Taco2."

Can you share your implementation Taco2? (if possible, then with a pre-trained model)
