### ISSUE TITLE
tacotron2 and waveglow

### ISSUE THREAD

**Issue by ireneb612** [CorentinJ/Real-Time-Voice-Cloning#878]
Why not substituting the current models with later versions one? 
Both Tacotron2 and Waveglow are implemented in pytorch.

**Comment by blue-fish** [comment]
There is no reason the models can't be substituted with more recent ones. Just need someone to work on it.

**Comment by e0xextazy** [comment]
> There is no reason the models can't be substituted with more recent ones. Just need someone to work on it.

If you can tell me how to do it in detail, I can try it.

**Comment by blue-fish** [comment]
I will provide guidance to those who can work independently and will contribute the results as open source.

First task is to get our toolbox to use NVIDIA's pretrained Tacotron2 in place of our synthesizer. The result of this step will be a single voice TTS since the NVIDIA model does not support voice cloning.
* Get model files from https://github.com/NVIDIA/tacotron2
* Use Griffin-Lim as the vocoder, not Waveglow. The info you need to use NVIDIA's pretrained model can be found in [tacotron2:hparams.py](https://github.com/NVIDIA/tacotron2/blob/master/hparams.py) and [tacotron2:layers.py](https://github.com/NVIDIA/tacotron2/blob/master/layers.py)
* Rule 1: You're not allowed to modify any toolbox files except for [demo_toolbox.py](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/demo_toolbox.py).
* Rule 2: You must use [synthesizer/inference.py](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/synthesizer/inference.py). Try to change it as little as possible.
    * Hint: because the NVIDIA model does not support voice cloning, do not pass the speaker embedding to it.

By the way, this is very similar to how I started working on #472.

**Comment by e0xextazy** [comment]
How should the architecture of the Tacotron 2 be modified to be able to clone a voice?

**Comment by blue-fish** [comment]
We'll get to that when the above task is complete.

**Comment by e0xextazy** [comment]
okay, I will write tomorrow.

**Comment by e0xextazy** [comment]
It's just that I already tried to implement taco 2 myself, and now it is learning, but it seems to me that I did something wrong, because my alignments in the 40k range look something like this
![Снимок экрана 2021-11-02 в 14 07 41](https://user-images.githubusercontent.com/49094658/139898421-78b8424d-f9e6-41d4-9dcb-dcc5283a3d41.png)
![Снимок экрана 2021-11-02 в 14 07 52](https://user-images.githubusercontent.com/49094658/139898450-bf54ad27-74c9-4b09-b4a8-2260964b2091.png)
![Снимок экрана 2021-11-02 в 14 08 13](https://user-images.githubusercontent.com/49094658/139898459-8750b999-598b-4f28-b81e-b12363e467bd.png)

**Comment by blue-fish** [comment]
> It's just that I already tried to implement taco 2 myself

I was not aware of this. If you have made progress on integrating Tacotron2 into this repo, share your code and we can start from there.

The approach I suggest is to first try the pretrained models in the toolbox UI to make sure everything is integrated properly. Once that is working, it is a good foundation for remaining work.

**Comment by e0xextazy** [comment]
I didn’t quite use this repository and didn’t integrate into it, but I was inspired by it. I've been researching your repository for a very long time. Now I will tell you how I implemented everything. In the second tacotron, the input to the attention layer has dimension 512, I concatenate to it the speaker embedding vector of dimension 256 and after that I apply the linear layer 768 -> 512

**Comment by blue-fish** [comment]
> In the second tacotron, the input to the attention layer has dimension 512, I concatenate to it the speaker embedding vector of dimension 256 and after that I apply the linear layer 768 -> 512

Try it without the "linear layer 768 -> 512". That is introducing an information bottleneck which is making it difficult to learn attention.

**Comment by blue-fish** [comment]
@e0xextazy I am going to mark the previous set of posts as off-topic. If you are able to contribute to this repo, it would be appreciated. If not, I understand.

**Comment by e0xextazy** [comment]
Maybe we should create some kind of space where we can communicate? I think the maximum I can share is a model, weights and a fairly detailed guide(without extending the code of this repository), but this still needs to be discussed with the company's management.

**Comment by blue-fish** [comment]
I propose that we use NVIDIA's Tacotron2 and train a voice cloning model from scratch on public datasets. Under these conditions, would your company need to be involved at all?

**Comment by blue-fish** [comment]
I have some exciting news to share, Nvidia's Tacotron2 has been integrated into my repo: https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/878_tacotron2

It is almost done, it just needs some modifications in the decoder to account for the speaker embedding. @e0xextazy If you are able, would you please share the changes you made to save me some time?

Both inference and training have been tested and work, but require CUDA for now. I am currently training a single-speaker model to make sure it can learn attention. After that, I will work on a pretrained model using LibriSpeech.

**Comment by blue-fish** [comment]
Training outputs at 7500 steps. It has learned attention, but the mel prediction is not as good as Tacotron1 at a similar stage. Perhaps the implementation of reduction factor can be improved.

### Tacotron2, r=7, steps=7500
![image](https://user-images.githubusercontent.com/67130644/141648154-994d67cf-4c53-4a6b-bc21-bc0884c99c04.png)
![attention_step_7500_sample_1](https://user-images.githubusercontent.com/67130644/141648168-324ae1c4-7410-4530-b7e3-a3aba809c36c.png)

### Tacotron1, r=2, steps=7500
![image](https://user-images.githubusercontent.com/67130644/141648510-833d19aa-68ff-40d1-8569-efaddd7f0b4d.png)

**Comment by blue-fish** [comment]
If you look carefully at the predicted spectrogram for `hparams.n_frames_per_step=7` above, you'll see some artifacts in the spectrogram. I don't have an explanation for this. But it does not happen when `hparams.n_frames_per_step=1`, after a sufficient number of steps have been trained.

**Comment by blue-fish** [comment]
@e0xextazy My implementation of SV2TTS in Nvidia Taco2: https://github.com/blue-fish/Real-Time-Voice-Cloning/commit/f9ad04373ffc0309295eb36ca73f8c27143cf2e6

**Comment by e0xextazy** [comment]
> I have some exciting news to share, Nvidia's Tacotron2 has been integrated into my repo: https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/878_tacotron2
> 
> It is almost done, it just needs some modifications in the decoder to account for the speaker embedding. @e0xextazy If you are able, would you please share the changes you made to save me some time?
> 
> Both inference and training have been tested and work, but require CUDA for now. I am currently training a single-speaker model to make sure it can learn attention. After that, I will work on a pretrained model using LibriSpeech.

What do you want me to provide you with? I do not understand the request.

**Comment by e0xextazy** [comment]
Dear blue-fish, could you give more advice on preparing data for training? Maybe you can combine some datasets together for better results and so on. 
Can you tell me briefly what has been done and what else needs to be done in your opinion?

**Comment by e0xextazy** [comment]
> Both inference and training have been tested and work, but require CUDA for now. I am currently training a single-speaker model to make sure it can learn attention. After that, I will work on a pretrained model using LibriSpeech.

One question that interests me is why are you going to use LibriSpeech and not LibriTTS? Are they different in some way?

**Comment by blue-fish** [comment]
> What do you want me to provide you with? I do not understand the request.

At the time, I wanted your code changes to add the speaker embedding. But after I finished checking the model with a single speaker dataset, I went ahead and made the code change myself in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/878#issuecomment-968587719 .

> One question that interests me is why are you going to use LibriSpeech and not LibriTTS? Are they different in some way?

LibriTTS is the better dataset, because the utterances are shorter and the transcripts contain punctuation. However, the punctuation does make it a little harder for the model to learn. I have already done a lot of experiments with LibriSpeech so I start with that one to benchmark the model against others I have developed.

> Dear blue-fish, could you give more advice on preparing data for training? Maybe you can combine some datasets together for better results and so on.
Can you tell me briefly what has been done and what else needs to be done in your opinion?

I am still trying to get a good TTS based on a single dataset: matching the results in the Tacotron 1/2 and SV2TTS papers. There is still a quality difference between our synthesizer and the one that Google demonstrated 3 years ago.

**Comment by e0xextazy** [comment]
@blue-fish Can I contact you outside of Github?

**Comment by blue-fish** [comment]
@e0xextazy Please contact me here. Keep in mind that I only provide assistance for open-source projects, and only as my time and interest allow.

**Comment by e0xextazy** [comment]
This is what I have at the moment. I am also attaching the hyperparameters of training. Is there any way you could comment on the learning process?
[hparams.txt](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/7561228/hparams.txt)
I can't attach the archive as a file (some internal error on github), so I'm sharing a link to google drive where you can download it
https://drive.google.com/file/d/1znYM_WHRbQZb9AjADZXbP9UJ_is2t-Gx/view?usp=sharing

**Comment by blue-fish** [comment]
> My Mel-spectrograms look very bad, what can this be due to?

I have been comparing my LibriSpeech training plots to Taco2 with the old Tensorflow repo and quality is the same. When compared to Taco1, the training mels look comparatively worse. But Taco2 inference quality is still good.

**Comment by e0xextazy** [comment]
How much do you think a model needs to be trained?  for example on a LibriTTS dataset consisting of 460 hours of audio data.  perhaps it is a certain number of steps or some value of the error function, at which the output will be good.  What else do you think about LibriTTS data processing?  it might be worth changing the current pipeline.  If my results are good, I can share the model weights for a sampling rate of 22050
