### ISSUE TITLE
Vocoder Diverging

### ISSUE THREAD

**Issue by Bebaam** [CorentinJ/Real-Time-Voice-Cloning#881]
Hey,
I am currently training a vocoder for another language from scratch (48k sample Rate). For this purpose, I used speech data which I manually tested for quality (at least audios).
Then I already trained a synthesizer (which learned attention successfully) and use it for preprocessing the vocoder. I changed the parameter accordingly:

sample_rate = 48000,
n_fft = 2400,
num_mels = 80,
hop_size = 600,
win_size = 2400

Furthermore, to match hop_length, I changed voc_upsample_factors to (5, 5, 8, 3).
I then tried to train the model but it diverges all the time.
Do you have an idea why this is the case? I trained with batch_size = 100, one model with voc_mode = 'RAW' for 600k steps and one with 'MOL' for 700k steps, but both always diverge at some point (and quality gets awful then).

Thanks in advance :)

**Comment by Bebaam** [comment]
I also tested with other voc upsample_factor (5,8,15), but without success.

**Comment by blue-fish** [comment]
No idea why this is happening. Can you successfully train a vocoder on the same dataset, but at a lower sample rate?

**Comment by Bebaam** [comment]
I didn't try it, but will give it a try with 16k to see whether it is training successfully (even if speed is then 3x).

**Comment by blue-fish** [comment]
Actually, it would make sense to first try training on the ground truth mels (in `<datasets_root>/SV2TTS/synthesizer/mels`) to confirm the problem repeats there too.

Then use `synthesizer_preprocess_audio.py` to process the dataset again at 16k, and train a vocoder on the 16k ground truth mels. For an equal comparison set `trim_silence = False` in synthesizer/hparams.py , because webrtcvad works at 16k but not 48k.

If 48k ground truth fails, while 16k GT works, then we can probably conclude it is an issue of the vocoder model. Though I'm not sure anything could be done in that case.

**Comment by Bebaam** [comment]
Okay thank you, and also thank you for all your support here!

I will then follow these steps now. If it does not work, I will change to 16k.

**Comment by blue-fish** [comment]
Did 48k ground truth work?

**Comment by Bebaam** [comment]
I just wanted to clean up a bit. As I can only train with 0.5 steps/s and as I train over colab only, it will take some time. The first test was not that promising, sometimes loss climbs up let's say from 4.1 to 4.8. But I am not sure if it matters with only a few thousand steps. Generally, should the loss never climb in this way (at least after certain amount of steps e.g. 100k,500k)?

I'll attend a picture where the loss in case of usual mels-gta training sometimes randomly went up and audio results are just noise afterwards. Maybe it gets better after e.g. 1 million steps?
![vocoderErrorRising](https://user-images.githubusercontent.com/44262699/140233017-a1af3c39-317e-47b6-8bf1-7a77de82de96.png)
