### ISSUE TITLE
Advice on bad performance

### ISSUE THREAD

**Issue by ireneb612** [CorentinJ/Real-Time-Voice-Cloning#891]
I trained the Synthesizer and the Vocoder for the italian language, but I kept the pretrined english encoder. While training, the generated mels were very good (for the synthesizer) and also the wavs for the vocoder where very good. However whn I try to do some inference the performance is really bad! Do yo have any idea why?
Maybe I didn't train enought the synthesizer (82k epochs) .... but still the training results were great...

**Comment by blue-fish** [comment]
The training mels are good because the decoder in the Tacotron model is allowed to see the ground truth mel that it is trying to construct. We give it a frame of the real spectrogram, and ask it to predict the next frame. Then we give it the next ground truth frame, and ask it to predict another. This training technique is called teacher forcing.

For inference, we don't provide a ground truth mel, so the decoder is on its own. It starts from zero (called the "GO frame" in the papers) and synthesizes 1 frame. Without the ground truth, it always needs to use its last predicted mel to synthesize the next. It is not always numerically stable, and the predictions will eventually break down producing unintelligible output. This is why we recommend synthesizing one sentence at a time.

During inference, Tacotron relies on the attention mechanism to tell it which part of the text input to synthesize at each step. Attention is very important for inference, so you'll want to make sure it was trained well. The alignment plots during training should contain a monotonic line.
