### ISSUE TITLE
Pretrained.pt (Bluefish models link ) seems missing? 

### ISSUE THREAD

**Issue by RobbeW** [CorentinJ/Real-Time-Voice-Cloning#929]
Hi, I am testing / running this code in a class project and noticed today that the pretrained.pt file in synth, vocoder and encoder (previously stored in /saved_models and /saved_models/pretrained/ ) seems missing?

**Comment by RobbeW** [comment]
Aha, I guess issue #928 answers my concern, but kinda does not solve it. (ghost made me miss that this comment was from BlueFish).

**Comment by sveneschlbeck** [comment]
@RobbeW I do, this is a hell of a lucky day we're having. I coincidentally downloaded the repo two days back or so but were not able to do something yet. This needs to be fixed, otherwise the link in the README is leading to an error page, too.

The files are too big for an upload, I'll try to add them in a new commit, will keep you posted

@CorentinJ What are you proposing on doing here?

**Comment by sveneschlbeck** [comment]
@RobbeW @CorentinJ We got a problem, the files are way too large to just upload them and Git LFS is not working on forked repos, so we really depend on @CorentinJ to add or restore them...

**Comment by AlexSteveChungAlvarez** [comment]
Hello, @RobbeW!  I also have the files, I have been trying to train a spanish model for a month, with no luck. I'm also doing a class project. I can pass you the files via gmail or drive as a fast solution for you if you need them fast. By the way, I need some help with the work of training in spanish, since I'm running out of time and the datasets I have worked with haven't given me results (#789).

**Comment by sveneschlbeck** [comment]
@RobbeW In the docs, there's still an initial commit ``.zip`` file: https://drive.google.com/file/d/1n1sPXvT34yXFLT47QZA6FIRGrwMeSsZc/view Should contain all three pretrains according to the file size

**Comment by AlexSteveChungAlvarez** [comment]
That should work for him.

> @RobbeW In the docs, there's still an initial commit `.zip` file: https://drive.google.com/file/d/1n1sPXvT34yXFLT47QZA6FIRGrwMeSsZc/view Should contain all three pretrains according to the file size

**Comment by sveneschlbeck** [comment]
@RobbeW @AlexSteveChungAlvarez This is a pretty good example of why we should definitely improve the docs on this repo. There were several people wishing tutorials on trainings (also in other languages) and deleting pretrained models/accounts without notification is something that should NEVER happen. Don't know what went wrong there...

Should wait for @CorentinJ `s opinion

**Comment by RobbeW** [comment]
@sveneschlbeck @AlexSteveChungAlvarez thanks a lot for the help. Kinda also my own fault, since I used the Colab version of the code containing paths to the three pretrained.pt files, which relied a !wget and the model blue-fish contributed. I should have, at least once, bothered to make a local copy of the file tree. 

I will give it a go with the G-Drive link above. Will try and figure out how to adjust the code to use the synthesizers multiple files, instead of the pretrained.pt single file path reference. 

If I can contribute in any way, let me know. If some solution comes out of this for my classes and students, I owe you all a coffee / beer.

**Comment by AlexSteveChungAlvarez** [comment]
Can any of you help me with the spanish model for the synthesizer? Issue #789 has my work until last week, but since then I just tried with subsamples of the last dataset I used for training. It hasn't given me good results, though. I think I will need to find another spanish dataset. The main problem is that I just have 1 month left to achieve it and each try has taken me about 1 week.

**Comment by delyro** [comment]
> @RobbeW In the docs, there's still an initial commit `.zip` file: https://drive.google.com/file/d/1n1sPXvT34yXFLT47QZA6FIRGrwMeSsZc/view Should contain all three pretrains according to the file size

This file **does not contain** valid pretrained model for synthesizer.

**Comment by AlexSteveChungAlvarez** [comment]
@Tymoteusz pointed out this does not contain the synthetizer pretrained model, but I don't know why the comment is not here anymore. I read it and uploaded the 3 pretrained models to this drive: https://drive.google.com/drive/folders/1lb-LlS8Sx9RqcGzuV6GxvKHk-PC9TqQx?usp=sharing . It is not a zip, so anyone who needs the models may download each of them. They are ordered in the original structure.

**Comment by delyro** [comment]
> @Tymoteusz pointed out this does not contain the synthetizer pretrained model, but I don't know why the comment is not here anymore. I read it and uploaded the 3 pretrained models to this drive: https://drive.google.com/drive/folders/1lb-LlS8Sx9RqcGzuV6GxvKHk-PC9TqQx?usp=sharing . It is not a zip, so anyone who needs the models may download each of them. They are ordered in the original structure.
> 
> > @RobbeW In the docs, there's still an initial commit `.zip` file: https://drive.google.com/file/d/1n1sPXvT34yXFLT47QZA6FIRGrwMeSsZc/view Should contain all three pretrains according to the file size

Apparently the archive mentioned earlier contains older models which are not compatible with current master branch ([source](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models/2cd3887f379d4921b193214973b463043efa5c23)).

I have tested your pretrained models and it works without any problems 👍

**Comment by nihao88** [comment]
does anybody plan to put pretrained models  in 1 wget accessible archive as before?:)

**Comment by RobbeW** [comment]
Tested the pretrained.pt models and they work! Marvelous and a big thanks! 
I'll store them locally this time and have a version in a cloud service so my students can !wget the files (using OneDrive)
If Sven or CoretinJ would deem it necessary to store critical files on a more secure cloud storage, I'm willing to chip in.

**Comment by RobbeW** [comment]
@AlexSteveChungAlvarez Sorry I couldn't help you with the Spanish model last week, I don't have the resources or skill to do so, but maybe [this new paper](https://edresson.github.io/YourTTS/) might help you reach that goal and deadline (TTS language synthesis, zero shot, low resource languages ...)

**Comment by AlexSteveChungAlvarez** [comment]
This paper seems very interesting, I already had a quick look at Coqui TTS, which is the tool they used for their experiments (Coqui TTS was developed by the ex team mozilla). Hopefully I cant take a look at it later. Maybe you can give me a hand in understanding Coqui?
I think you should close this issue since the issue was solved already, and we should talk about the helping hand in #789 :) .

**Comment by Dannypeja** [comment]
@AlexSteveChungAlvarez  could you check on your local machine when the files were created? We are trying to figure out over here #942 if those from 06.02.21 are latest, thus RTVC 7.  If your Date is newer, then we are behind. 
If I download unzipped files from your drive they get date of today.

**Comment by AlexSteveChungAlvarez** [comment]
Mine have the same date! 06/02/2021

**Comment by Dannypeja** [comment]
Okay so we can assume those are latest and belong to RTVC 7
